// Code generated from the fixtures in testdata. DO NOT EDIT BY HAND.
//
// Regenerate by re-running the extraction described in
// testdata/servertest-ini.keys and testdata/sandboxvars.keys against a real
// Project Zomboid dedicated server install, then rebuilding this file from
// them. The fixtures are the record of what the game said; this file is only
// a Go rendering of them.
//
// It is generated rather than hand-written because Compile writes both config
// files whole: a key missing from here is a key Garrison would silently
// delete from an operator's server. Completeness matters more than curation,
// and 413 hand-typed literals would not stay complete.

package zomboid

// setting is one config key as the game defines it.
type setting struct {
	Key     string
	Type    string // bool, int, float, string
	Default any
	// Options is the game's own numbering for a graded setting, in order.
	// Empty for everything that is not one.
	Options []option
}

type option struct {
	Value int
	Label string
}

// iniSettings is every key in servertest.ini, in the order the server writes them.
var iniSettings = []setting{
	{Key: "PVP", Type: "bool", Default: true},
	{Key: "PVPLogToolChat", Type: "bool", Default: true},
	{Key: "PVPLogToolFile", Type: "bool", Default: true},
	{Key: "PauseEmpty", Type: "bool", Default: true},
	{Key: "GlobalChat", Type: "bool", Default: true},
	{Key: "ChatStreams", Type: "string", Default: "s,r,a,w,y,sh,f,all"},
	{Key: "Open", Type: "bool", Default: true},
	{Key: "ServerWelcomeMessage", Type: "string", Default: "Welcome to Project Zomboid Multiplayer! <LINE> <LINE> To interact with the Chat panel: press Tab, T, or Enter. <LINE> <LINE> The Tab key will change the target stream of the message. <LINE> <LINE> Global Streams: /all <LINE> Local Streams: /say, /yell <LINE> Special Steams: /whisper, /safehouse, /faction. <LINE> <LINE> Press the Up arrow to cycle through your message history. Click the Gear icon to customize chat. <LINE> <LINE> Happy surviving!"},
	{Key: "DisplayUserName", Type: "bool", Default: true},
	{Key: "ShowFirstAndLastName", Type: "bool", Default: false},
	{Key: "UsernameDisguises", Type: "bool", Default: false},
	{Key: "HideDisguisedUserName", Type: "bool", Default: false},
	{Key: "SwitchZombiesOwnershipEachUpdate", Type: "bool", Default: false},
	{Key: "SpawnPoint", Type: "string", Default: "0,0,0"},
	{Key: "SafetySystem", Type: "bool", Default: true},
	{Key: "ShowSafety", Type: "bool", Default: true},
	{Key: "SafetyToggleTimer", Type: "int", Default: 2},
	{Key: "SafetyCooldownTimer", Type: "int", Default: 3},
	{Key: "SafetyDisconnectDelay", Type: "int", Default: 60},
	{Key: "SpawnItems", Type: "string", Default: ""},
	{Key: "DefaultPort", Type: "int", Default: 16261},
	{Key: "UDPPort", Type: "int", Default: 16262},
	{Key: "ResetID", Type: "int", Default: 1987082},
	{Key: "Mods", Type: "string", Default: "BetterSortCC;P4HasBeenRead;ChuckleberryFinnAlertSystem;errorMagnifier;SkillRecoveryJournal;MapLegendUI;ProximityInventory;KillCount;CombatText;RainCleansBlood;RepairAnyClothes;MapSymbolSizeSlider;SwapIt;manageContainers;P4TidyUpMeister;UnifiedCarryWeightFramework;1299328280/ToadTraits;VehicleRepairOverhaul;MoreBuilds;FH;Authentic Z - Current;RiskyInspectWeapon;HBVCEFb42;ReloadAllMagazines;damnlib;isoContainers;KI5trailers;NoLighterNeeded;NeatUI_Framework;Project_Cook;FunctionalAppliances2;VanillaFoodsExpanded;BLTAnnotations;TreesHaveLoot;TotalWeightRebalance;92amgeneralM998;92amgeneralM998extra;86oshkoshP19A;82oshkoshM911;78amgeneralM35A2;78amgeneralM35A2extra;78amgeneralM49A2C;78amgeneralM50A3;78amgeneralM62;91range;92nissanGTR;70dodge;67commando;83amgeneralM923;83amgeneralM923extra;84merc;97bushmaster;88chevyS10;82jeepJ10;82jeepJ10t;86fordE150;86fordE150dnd;86fordE150expanded;86fordE150mm;86fordE150pd;92fordCVPI;90fordF350ambulance;90pierceArrow;89fordBronco;67gt500;87fordB700;69camaro;93fordF350;89trooper;49powerWagon;70barracuda;63beetle;69mini;69mini_ItalianJob;69mini_MrBean;69mini_PitbullSpecial;90bmwE30;59meteor;ECTO1;93townCar;EQUIPMENT_UI;SWMG;GunsOfMarz;hf_point_blank;SimpleSilencers;AutoReload;Run and Reload;Buttstroke;TacHold Complete;ammomaker;HBAC;AmmoLootDropB42;AliceGear;alicesWeaponSling;alicesWeaponSlingRadialMenu;Military_Tool_Kit;BCGTools;BCGRareWeapons"},
	{Key: "Map", Type: "string", Default: "Muldraugh, KY"},
	{Key: "DoLuaChecksum", Type: "bool", Default: false},
	{Key: "DenyLoginOnOverloadedServer", Type: "bool", Default: true},
	{Key: "Public", Type: "bool", Default: false},
	{Key: "PublicName", Type: "string", Default: "Camden's Zomboid Server"},
	{Key: "PublicDescription", Type: "string", Default: "Private server - password required"},
	{Key: "MaxPlayers", Type: "int", Default: 8},
	{Key: "PingLimit", Type: "int", Default: 0},
	{Key: "SafehousePreventsLootRespawn", Type: "bool", Default: true},
	{Key: "DropOffWhiteListAfterDeath", Type: "bool", Default: false},
	{Key: "NoFire", Type: "bool", Default: false},
	{Key: "AnnounceDeath", Type: "bool", Default: false},
	{Key: "AnnounceAnimalDeath", Type: "bool", Default: false},
	{Key: "SaveWorldEveryMinutes", Type: "int", Default: 15},
	{Key: "PlayerSafehouse", Type: "bool", Default: false},
	{Key: "AdminSafehouse", Type: "bool", Default: false},
	{Key: "SafehouseAllowTrepass", Type: "bool", Default: true},
	{Key: "SafehouseAllowFire", Type: "bool", Default: true},
	{Key: "SafehouseAllowLoot", Type: "bool", Default: true},
	{Key: "SafehouseAllowRespawn", Type: "bool", Default: false},
	{Key: "SafehouseDaySurvivedToClaim", Type: "int", Default: 0},
	{Key: "SafeHouseRemovalTime", Type: "int", Default: 144},
	{Key: "SafehouseAllowNonResidential", Type: "bool", Default: false},
	{Key: "SafehouseDisableDisguises", Type: "bool", Default: true},
	{Key: "MaxSafezoneSize", Type: "int", Default: 20000},
	{Key: "AllowDestructionBySledgehammer", Type: "bool", Default: true},
	{Key: "SledgehammerOnlyInSafehouse", Type: "bool", Default: false},
	{Key: "War", Type: "bool", Default: false},
	{Key: "WarStartDelay", Type: "int", Default: 600},
	{Key: "WarDuration", Type: "int", Default: 3600},
	{Key: "WarSafehouseHitPoints", Type: "int", Default: 3},
	{Key: "ServerPlayerID", Type: "int", Default: 0},
	{Key: "RCONPort", Type: "int", Default: 27015},
	{Key: "RCONPassword", Type: "string", Default: ""},
	{Key: "DiscordEnable", Type: "bool", Default: false},
	{Key: "DiscordToken", Type: "string", Default: ""},
	{Key: "DiscordChatChannel", Type: "string", Default: ""},
	{Key: "DiscordLogChannel", Type: "string", Default: ""},
	{Key: "DiscordCommandChannel", Type: "string", Default: ""},
	{Key: "WebhookAddress", Type: "string", Default: ""},
	{Key: "Password", Type: "string", Default: ""},
	{Key: "MaxAccountsPerUser", Type: "int", Default: 2},
	{Key: "AllowCoop", Type: "bool", Default: true},
	{Key: "SleepAllowed", Type: "bool", Default: false},
	{Key: "SleepNeeded", Type: "bool", Default: false},
	{Key: "KnockedDownAllowed", Type: "bool", Default: false},
	{Key: "SneakModeHideFromOtherPlayers", Type: "bool", Default: true},
	{Key: "UltraSpeedDoesnotAffectToAnimals", Type: "bool", Default: false},
	{Key: "WorkshopItems", Type: "string", Default: "2313387159;2544353492;2503622437;2896041179;2710167561;2847184718;2553809727;2286124931;2956146279;2142622992;2734705913;2366717227;2650547917;2769706949;1299328280;2757712197;515555911;2447729538;2335368829;2948824747;3610677934;2920899878;2625625421;3330403100;2714198296;3077900375;3490188370;3042138819;3577903007;2815560151;2951270166;3171167894;3508537032;3682045254;3786993262;2642541073;2566953935;2618213077;2799152995;2409333430;2846036306;2873290424;2478247379;2811383142;2805630347;2897390033;2886832936;2886832257;2870394916;2962175696;2952802178;2942793445;2886833398;3026723485;3110911330;2991201484;3073430075;2932549988;2900580391;2913633066;3005903549;2937786633;3110913021;2772575623;2932547723;2950902979;3722064198;3722134990;2990322197;3309896124;3389448389;3397207461;3394044313;3693258802;3420478458;2788256295;3637364024;3389050623;3610005735;3775549570;2705406713;2423906082;2432621382"},
	{Key: "SteamScoreboard", Type: "bool", Default: false},
	{Key: "SteamVAC", Type: "bool", Default: true},
	{Key: "UPnP", Type: "bool", Default: false},
	{Key: "VoiceEnable", Type: "bool", Default: true},
	{Key: "VoiceMinDistance", Type: "float", Default: 10.0},
	{Key: "VoiceMaxDistance", Type: "float", Default: 100.0},
	{Key: "Voice3D", Type: "bool", Default: true},
	{Key: "SpeedLimit", Type: "float", Default: 70.0},
	{Key: "LoginQueueEnabled", Type: "bool", Default: false},
	{Key: "LoginQueueConnectTimeout", Type: "int", Default: 60},
	{Key: "server_browser_announced_ip", Type: "string", Default: ""},
	{Key: "PlayerRespawnWithSelf", Type: "bool", Default: false},
	{Key: "PlayerRespawnWithOther", Type: "bool", Default: false},
	{Key: "FastForwardMultiplier", Type: "float", Default: 40.0},
	{Key: "DisableSafehouseWhenOwnerConnected", Type: "bool", Default: false},
	{Key: "Faction", Type: "bool", Default: true},
	{Key: "FactionDaySurvivedToCreate", Type: "int", Default: 0},
	{Key: "FactionPlayersRequiredForTag", Type: "int", Default: 1},
	{Key: "DisableRadioStaff", Type: "bool", Default: false},
	{Key: "DisableRadioAdmin", Type: "bool", Default: true},
	{Key: "DisableRadioGM", Type: "bool", Default: true},
	{Key: "DisableRadioOverseer", Type: "bool", Default: false},
	{Key: "DisableRadioModerator", Type: "bool", Default: false},
	{Key: "DisableRadioInvisible", Type: "bool", Default: true},
	{Key: "ClientCommandFilter", Type: "string", Default: "-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart"},
	{Key: "ClientActionLogs", Type: "string", Default: "ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;"},
	{Key: "PerkLogs", Type: "bool", Default: true},
	{Key: "ItemNumbersLimitPerContainer", Type: "int", Default: 0},
	{Key: "BloodSplatLifespanDays", Type: "int", Default: 0},
	{Key: "AllowNonAsciiUsername", Type: "bool", Default: false},
	{Key: "BanKickGlobalSound", Type: "bool", Default: true},
	{Key: "RemovePlayerCorpsesOnCorpseRemoval", Type: "bool", Default: false},
	{Key: "TrashDeleteAll", Type: "bool", Default: false},
	{Key: "PVPMeleeWhileHitReaction", Type: "bool", Default: false},
	{Key: "MouseOverToSeeDisplayName", Type: "bool", Default: true},
	{Key: "HidePlayersBehindYou", Type: "bool", Default: true},
	{Key: "PVPMeleeDamageModifier", Type: "float", Default: 30.0},
	{Key: "PVPFirearmDamageModifier", Type: "float", Default: 50.0},
	{Key: "CarEngineAttractionModifier", Type: "float", Default: 0.5},
	{Key: "PlayerBumpPlayer", Type: "bool", Default: false},
	{Key: "MapRemotePlayerVisibility", Type: "int", Default: 1},
	{Key: "BackupsCount", Type: "int", Default: 10},
	{Key: "BackupsOnStart", Type: "bool", Default: true},
	{Key: "BackupsOnVersionChange", Type: "bool", Default: true},
	{Key: "BackupsPeriod", Type: "int", Default: 60},
	{Key: "DisableVehicleTowing", Type: "bool", Default: false},
	{Key: "DisableTrailerTowing", Type: "bool", Default: false},
	{Key: "DisableBurntTowing", Type: "bool", Default: false},
	{Key: "BadWordListFile", Type: "string", Default: ""},
	{Key: "GoodWordListFile", Type: "string", Default: ""},
	{Key: "BadWordPolicy", Type: "int", Default: 3},
	{Key: "BadWordReplacement", Type: "string", Default: "[HIDDEN]"},
	{Key: "AntiCheatSafety", Type: "int", Default: 4},
	{Key: "AntiCheatSpeed", Type: "int", Default: 4},
	{Key: "AntiCheatNoClip", Type: "int", Default: 4},
	{Key: "AntiCheatHit", Type: "int", Default: 4},
	{Key: "AntiCheatPacketException", Type: "int", Default: 4},
	{Key: "AntiCheatPermission", Type: "int", Default: 4},
	{Key: "AntiCheatXP", Type: "int", Default: 4},
	{Key: "AntiCheatSafeHouse", Type: "int", Default: 4},
	{Key: "AntiCheatPlayer", Type: "int", Default: 4},
	{Key: "AntiCheatChecksum", Type: "int", Default: 4},
	{Key: "MultiplayerStatisticsPeriod", Type: "int", Default: 1},
	{Key: "DisableScoreboard", Type: "bool", Default: false},
	{Key: "HideAdminsInPlayerList", Type: "bool", Default: false},
	{Key: "MaxPacketsPerSecond", Type: "int", Default: 300},
	{Key: "ShowCoordinates", Type: "bool", Default: false},
	{Key: "Seed", Type: "string", Default: "wiAwKKlhVOuZKiuQ"},
	{Key: "UsePhysicsHitReaction", Type: "bool", Default: false},
	{Key: "ChatMessageCharacterLimit", Type: "int", Default: 200},
	{Key: "ChatMessageSlowModeTime", Type: "int", Default: 3},
}

// sandboxSettings is every sandbox variable, with the game's Apocalypse-preset default.
var sandboxSettings = []setting{
	{Key: "Version", Type: "int", Default: 6},
	{Key: "Zombies", Type: "int", Default: 4, Options: []option{{1, "Insane"}, {2, "Very High"}, {3, "High"}, {4, "Normal"}, {5, "Low"}, {6, "None"}}},
	{Key: "Distribution", Type: "int", Default: 1, Options: []option{{1, "Urban Focused"}, {2, "Uniform"}}},
	{Key: "ZombieVoronoiNoise", Type: "bool", Default: true},
	{Key: "ZombieRespawn", Type: "int", Default: 4, Options: []option{{1, "High"}, {2, "Normal"}, {3, "Low"}, {4, "None"}}},
	{Key: "ZombieMigrate", Type: "bool", Default: true},
	{Key: "DayLength", Type: "int", Default: 4, Options: []option{{1, "15 Minutes"}, {2, "30 Minutes"}, {3, "1 Hour"}, {4, "1 Hour, 30 Minutes"}, {5, "2 Hours"}, {6, "3 Hours"}, {7, "4 Hours"}, {8, "5 Hours"}, {9, "6 Hours"}, {10, "7 Hours"}, {11, "8 Hours"}, {12, "9 Hours"}, {13, "10 Hours"}, {14, "11 Hours"}, {15, "12 Hours"}, {16, "13 Hours"}, {17, "14 Hours"}, {18, "15 Hours"}, {19, "16 Hours"}, {20, "17 Hours"}, {21, "18 Hours"}, {22, "19 Hours"}, {23, "20 Hours"}, {24, "21 Hours"}, {25, "22 Hours"}, {26, "23 Hours"}, {27, "Real-time"}}},
	{Key: "StartYear", Type: "int", Default: 1},
	{Key: "StartMonth", Type: "int", Default: 7, Options: []option{{1, "January"}, {2, "February"}, {3, "March"}, {4, "April"}, {5, "May"}, {6, "June"}, {7, "July"}, {8, "August"}, {9, "September"}, {10, "October"}, {11, "November"}, {12, "December"}}},
	{Key: "StartDay", Type: "int", Default: 9},
	{Key: "StartTime", Type: "int", Default: 2, Options: []option{{1, "7 AM"}, {2, "9 AM"}, {3, "12 PM"}, {4, "2 PM"}, {5, "5 PM"}, {6, "9 PM"}, {7, "12 AM"}, {8, "2 AM"}, {9, "5 AM"}}},
	{Key: "DayNightCycle", Type: "int", Default: 1, Options: []option{{1, "Normal"}, {2, "Endless Day"}, {3, "Endless Night"}}},
	{Key: "ClimateCycle", Type: "int", Default: 1, Options: []option{{1, "Normal"}, {2, "No Weather"}, {3, "Endless Rain"}, {4, "Endless Storm"}, {5, "Endless Snow"}, {6, "Endless Blizzard"}}},
	{Key: "FogCycle", Type: "int", Default: 1, Options: []option{{1, "Normal"}, {2, "No Fog"}, {3, "Endless Fog"}}},
	{Key: "WaterShut", Type: "int", Default: 2, Options: []option{{1, "Instant"}, {2, "0 - 30 Days"}, {3, "0 - 2 Months"}, {4, "0 - 6 Months"}, {5, "0 - 1 Year"}, {6, "0 - 5 Years"}, {7, "2 - 6 Months"}, {8, "6 - 12 Months"}, {9, "Disabled"}}},
	{Key: "ElecShut", Type: "int", Default: 2, Options: []option{{1, "Instant"}, {2, "14 - 30 Days"}, {3, "14 Days - 2 Months"}, {4, "14 Days - 6 Months"}, {5, "14 Days - 1 Year"}, {6, "14 Days - 5 Years"}, {7, "2 - 6 Months"}, {8, "6 - 12 Months"}, {9, "Disabled"}}},
	{Key: "AlarmDecay", Type: "int", Default: 2, Options: []option{{1, "Instant"}, {2, "0 - 30 Days"}, {3, "0 - 2 Months"}, {4, "0 - 6 Months"}, {5, "0 - 1 Year"}, {6, "0 - 5 Years"}}},
	{Key: "WaterShutModifier", Type: "int", Default: 14},
	{Key: "ElecShutModifier", Type: "int", Default: 14},
	{Key: "AlarmDecayModifier", Type: "int", Default: 14},
	{Key: "FoodLootNew", Type: "float", Default: 0.8},
	{Key: "LiteratureLootNew", Type: "float", Default: 0.6},
	{Key: "SkillBookLoot", Type: "float", Default: 0.6},
	{Key: "RecipeResourceLoot", Type: "float", Default: 0.6},
	{Key: "MedicalLootNew", Type: "float", Default: 0.6},
	{Key: "SurvivalGearsLootNew", Type: "float", Default: 0.6},
	{Key: "CannedFoodLootNew", Type: "float", Default: 0.6},
	{Key: "WeaponLootNew", Type: "float", Default: 0.6},
	{Key: "RangedWeaponLootNew", Type: "float", Default: 1.2},
	{Key: "AmmoLootNew", Type: "float", Default: 0.6},
	{Key: "MechanicsLootNew", Type: "float", Default: 0.6},
	{Key: "OtherLootNew", Type: "float", Default: 0.8},
	{Key: "ClothingLootNew", Type: "float", Default: 0.6},
	{Key: "ContainerLootNew", Type: "float", Default: 0.6},
	{Key: "KeyLootNew", Type: "float", Default: 0.4},
	{Key: "MediaLootNew", Type: "float", Default: 0.6},
	{Key: "MementoLootNew", Type: "float", Default: 0.6},
	{Key: "CookwareLootNew", Type: "float", Default: 0.6},
	{Key: "MaterialLootNew", Type: "float", Default: 0.6},
	{Key: "FarmingLootNew", Type: "float", Default: 0.6},
	{Key: "ToolLootNew", Type: "float", Default: 0.6},
	{Key: "RollsMultiplier", Type: "float", Default: 1.0},
	{Key: "RemoveStoryLoot", Type: "bool", Default: false},
	{Key: "RemoveZombieLoot", Type: "bool", Default: false},
	{Key: "ZombiePopLootEffect", Type: "int", Default: 0},
	{Key: "InsaneLootFactor", Type: "float", Default: 0.05},
	{Key: "ExtremeLootFactor", Type: "float", Default: 0.2},
	{Key: "RareLootFactor", Type: "float", Default: 0.6},
	{Key: "NormalLootFactor", Type: "float", Default: 1.0},
	{Key: "CommonLootFactor", Type: "float", Default: 2.0},
	{Key: "AbundantLootFactor", Type: "float", Default: 3.0},
	{Key: "Temperature", Type: "int", Default: 3, Options: []option{{1, "Very Cold"}, {2, "Cold"}, {3, "Normal"}, {4, "Hot"}, {5, "Very Hot"}}},
	{Key: "Rain", Type: "int", Default: 3, Options: []option{{1, "Very Dry"}, {2, "Dry"}, {3, "Normal"}, {4, "Rainy"}, {5, "Very Rainy"}}},
	{Key: "ErosionSpeed", Type: "int", Default: 4, Options: []option{{1, "Very Fast (20 Days)"}, {2, "Fast (50 Days)"}, {3, "Normal (100 Days)"}, {4, "Slow (200 Days)"}, {5, "Very Slow (500 Days)"}}},
	{Key: "ErosionDays", Type: "int", Default: 0},
	{Key: "Farming", Type: "int", Default: 3, Options: []option{{1, "Very Fast"}, {2, "Fast"}, {3, "Normal"}, {4, "Slow"}, {5, "Very Slow"}}},
	{Key: "CompostTime", Type: "int", Default: 2, Options: []option{{1, "1 Week"}, {2, "2 Weeks"}, {3, "3 Weeks"}, {4, "4 Weeks"}, {5, "6 Weeks"}, {6, "8 Weeks"}, {7, "10 Weeks"}, {8, "12 Weeks"}}},
	{Key: "StatsDecrease", Type: "int", Default: 3, Options: []option{{1, "Very Fast"}, {2, "Fast"}, {3, "Normal"}, {4, "Slow"}, {5, "Very Slow"}}},
	{Key: "NatureAbundance", Type: "int", Default: 3, Options: []option{{1, "Very Poor"}, {2, "Poor"}, {3, "Normal"}, {4, "Abundant"}, {5, "Very Abundant"}}},
	{Key: "Alarm", Type: "int", Default: 4, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}}},
	{Key: "LockedHouses", Type: "int", Default: 6, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}}},
	{Key: "StarterKit", Type: "bool", Default: false},
	{Key: "Nutrition", Type: "bool", Default: true},
	{Key: "FoodRotSpeed", Type: "int", Default: 3, Options: []option{{1, "Very Fast"}, {2, "Fast"}, {3, "Normal"}, {4, "Slow"}, {5, "Very Slow"}}},
	{Key: "FridgeFactor", Type: "int", Default: 3, Options: []option{{1, "Very Low"}, {2, "Low"}, {3, "Normal"}, {4, "High"}, {5, "Very High"}, {6, "No decay"}}},
	{Key: "SeenHoursPreventLootRespawn", Type: "int", Default: 0},
	{Key: "HoursForLootRespawn", Type: "int", Default: 0},
	{Key: "MaxItemsForLootRespawn", Type: "int", Default: 5},
	{Key: "ConstructionPreventsLootRespawn", Type: "bool", Default: true},
	{Key: "WorldItemRemovalList", Type: "string", Default: "\"Base.Hat, Base.Glasses, Base.Maggots, Base.Slug, Base.Slug2, Base.Snail, Base.Worm, Base.Dung_Mouse, Base.Dung_Rat\""},
	{Key: "HoursForWorldItemRemoval", Type: "float", Default: 24.0},
	{Key: "ItemRemovalListBlacklistToggle", Type: "bool", Default: false},
	{Key: "TimeSinceApo", Type: "int", Default: 1, Options: []option{{1, "0"}, {2, "1"}, {3, "2"}, {4, "3"}, {5, "4"}, {6, "5"}, {7, "6"}, {8, "7"}, {9, "8"}, {10, "9"}, {11, "10"}, {12, "11"}, {13, "12"}}},
	{Key: "PlantResilience", Type: "int", Default: 3, Options: []option{{1, "Very High"}, {2, "High"}, {3, "Normal"}, {4, "Low"}, {5, "Very Low"}}},
	{Key: "PlantAbundance", Type: "int", Default: 3, Options: []option{{1, "Very Poor"}, {2, "Poor"}, {3, "Normal"}, {4, "Abundant"}, {5, "Very Abundant"}}},
	{Key: "EndRegen", Type: "int", Default: 3, Options: []option{{1, "Very Fast"}, {2, "Fast"}, {3, "Normal"}, {4, "Slow"}, {5, "Very Slow"}}},
	{Key: "Helicopter", Type: "int", Default: 2, Options: []option{{1, "Never"}, {2, "Once"}, {3, "Sometimes"}, {4, "Often"}}},
	{Key: "MetaEvent", Type: "int", Default: 2, Options: []option{{1, "Never"}, {2, "Sometimes"}, {3, "Often"}}},
	{Key: "SleepingEvent", Type: "int", Default: 1, Options: []option{{1, "Never"}, {2, "Sometimes"}, {3, "Often"}}},
	{Key: "GeneratorFuelConsumption", Type: "float", Default: 0.1},
	{Key: "GeneratorSpawning", Type: "int", Default: 4, Options: []option{{1, "None (not recommended)"}, {2, "Insanely Rare"}, {3, "Extremely Rare"}, {4, "Rare"}, {5, "Normal"}, {6, "Common"}, {7, "Abundant"}}},
	{Key: "AnnotatedMapChance", Type: "int", Default: 4, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}}},
	{Key: "CharacterFreePoints", Type: "int", Default: 0},
	{Key: "ConstructionBonusPoints", Type: "int", Default: 3, Options: []option{{1, "Very Low"}, {2, "Low"}, {3, "Normal"}, {4, "High"}, {5, "Very High"}}},
	{Key: "NightDarkness", Type: "int", Default: 3, Options: []option{{1, "Pitch Black"}, {2, "Dark"}, {3, "Normal"}, {4, "Bright"}}},
	{Key: "NightLength", Type: "int", Default: 3, Options: []option{{1, "Always Night"}, {2, "Long"}, {3, "Normal"}, {4, "Short"}, {5, "Always Day"}}},
	{Key: "BoneFracture", Type: "bool", Default: true},
	{Key: "InjurySeverity", Type: "int", Default: 2, Options: []option{{1, "Low"}, {2, "Normal"}, {3, "High"}}},
	{Key: "HoursForCorpseRemoval", Type: "float", Default: 216.0},
	{Key: "DecayingCorpseHealthImpact", Type: "int", Default: 3, Options: []option{{1, "None"}, {2, "Low"}, {3, "Normal"}, {4, "High"}, {5, "Insane"}}},
	{Key: "ZombieHealthImpact", Type: "bool", Default: false},
	{Key: "BloodLevel", Type: "int", Default: 3, Options: []option{{1, "None"}, {2, "Low"}, {3, "Normal"}, {4, "High"}, {5, "Ultra Gore"}}},
	{Key: "ClothingDegradation", Type: "int", Default: 3, Options: []option{{1, "Disabled"}, {2, "Slow"}, {3, "Normal"}, {4, "Fast"}}},
	{Key: "FireSpread", Type: "bool", Default: true},
	{Key: "DaysForRottenFoodRemoval", Type: "int", Default: -1},
	{Key: "AllowExteriorGenerator", Type: "bool", Default: true},
	{Key: "MaxFogIntensity", Type: "int", Default: 1, Options: []option{{1, "Normal"}, {2, "Moderate"}, {3, "Low"}, {4, "None"}}},
	{Key: "MaxRainFxIntensity", Type: "int", Default: 1, Options: []option{{1, "Normal"}, {2, "Moderate"}, {3, "Low"}}},
	{Key: "EnableSnowOnGround", Type: "bool", Default: true},
	{Key: "AttackBlockMovements", Type: "bool", Default: true},
	{Key: "SurvivorHouseChance", Type: "int", Default: 3, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}, {7, "Always Tries"}}},
	{Key: "VehicleStoryChance", Type: "int", Default: 3, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}, {7, "Always Tries"}}},
	{Key: "ZoneStoryChance", Type: "int", Default: 3, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}, {7, "Always Tries"}}},
	{Key: "AllClothesUnlocked", Type: "bool", Default: false},
	{Key: "EnableTaintedWaterText", Type: "bool", Default: true},
	{Key: "EnableVehicles", Type: "bool", Default: true},
	{Key: "CarSpawnRate", Type: "int", Default: 3, Options: []option{{1, "None"}, {2, "Very Low"}, {3, "Low"}, {4, "Normal"}, {5, "High"}}},
	{Key: "ZombieAttractionMultiplier", Type: "float", Default: 1.0},
	{Key: "VehicleEasyUse", Type: "bool", Default: false},
	{Key: "InitialGas", Type: "int", Default: 2, Options: []option{{1, "Very Low"}, {2, "Low"}, {3, "Normal"}, {4, "High"}, {5, "Very High"}, {6, "Full"}}},
	{Key: "FuelStationGasInfinite", Type: "bool", Default: false},
	{Key: "FuelStationGasMin", Type: "float", Default: 0.0},
	{Key: "FuelStationGasMax", Type: "float", Default: 0.8},
	{Key: "FuelStationGasEmptyChance", Type: "int", Default: 20},
	{Key: "LockedCar", Type: "int", Default: 4, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}}},
	{Key: "CarGasConsumption", Type: "float", Default: 1.0},
	{Key: "CarGeneralCondition", Type: "int", Default: 3, Options: []option{{1, "Very Low"}, {2, "Low"}, {3, "Normal"}, {4, "High"}, {5, "Very High"}}},
	{Key: "CarDamageOnImpact", Type: "int", Default: 3, Options: []option{{1, "Very Low"}, {2, "Low"}, {3, "Normal"}, {4, "High"}, {5, "Very High"}}},
	{Key: "DamageToPlayerFromHitByACar", Type: "int", Default: 1, Options: []option{{1, "None"}, {2, "Low"}, {3, "Normal"}, {4, "High"}, {5, "Very High"}}},
	{Key: "TrafficJam", Type: "bool", Default: true},
	{Key: "CarAlarm", Type: "int", Default: 3, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}}},
	{Key: "PlayerDamageFromCrash", Type: "bool", Default: true},
	{Key: "SirenShutoffHours", Type: "float", Default: 0.0},
	{Key: "ChanceHasGas", Type: "int", Default: 2, Options: []option{{1, "Low"}, {2, "Normal"}, {3, "High"}}},
	{Key: "RecentlySurvivorVehicles", Type: "int", Default: 2, Options: []option{{1, "None"}, {2, "Low"}, {3, "Normal"}, {4, "High"}}},
	{Key: "MultiHitZombies", Type: "bool", Default: false},
	{Key: "RearVulnerability", Type: "int", Default: 3, Options: []option{{1, "Low"}, {2, "Medium"}, {3, "High"}}},
	{Key: "SirenEffectsZombies", Type: "bool", Default: true},
	{Key: "AnimalStatsModifier", Type: "int", Default: 4, Options: []option{{1, "Ultra Fast"}, {2, "Very Fast"}, {3, "Fast"}, {4, "Normal"}, {5, "Slow"}, {6, "Very Slow"}}},
	{Key: "AnimalMetaStatsModifier", Type: "int", Default: 4, Options: []option{{1, "Ultra Fast"}, {2, "Very Fast"}, {3, "Fast"}, {4, "Normal"}, {5, "Slow"}, {6, "Very Slow"}}},
	{Key: "AnimalPregnancyTime", Type: "int", Default: 4, Options: []option{{1, "Ultra Fast"}, {2, "Very Fast"}, {3, "Fast"}, {4, "Normal"}, {5, "Slow"}, {6, "Very Slow"}}},
	{Key: "AnimalAgeModifier", Type: "int", Default: 4, Options: []option{{1, "Ultra Fast"}, {2, "Very Fast"}, {3, "Fast"}, {4, "Normal"}, {5, "Slow"}, {6, "Very Slow"}}},
	{Key: "AnimalMilkIncModifier", Type: "int", Default: 4, Options: []option{{1, "Ultra Fast"}, {2, "Very Fast"}, {3, "Fast"}, {4, "Normal"}, {5, "Slow"}, {6, "Very Slow"}}},
	{Key: "AnimalWoolIncModifier", Type: "int", Default: 4, Options: []option{{1, "Ultra Fast"}, {2, "Very Fast"}, {3, "Fast"}, {4, "Normal"}, {5, "Slow"}, {6, "Very Slow"}}},
	{Key: "AnimalRanchChance", Type: "int", Default: 5, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}, {7, "Always"}}},
	{Key: "AnimalGrassRegrowTime", Type: "int", Default: 240},
	{Key: "AnimalMetaPredator", Type: "bool", Default: false},
	{Key: "AnimalMatingSeason", Type: "bool", Default: true},
	{Key: "AnimalEggHatch", Type: "int", Default: 4, Options: []option{{1, "Ultra Fast"}, {2, "Very Fast"}, {3, "Fast"}, {4, "Normal"}, {5, "Slow"}, {6, "Very Slow"}}},
	{Key: "AnimalSoundAttractZombies", Type: "bool", Default: true},
	{Key: "AnimalTrackChance", Type: "int", Default: 4, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}}},
	{Key: "AnimalPathChance", Type: "int", Default: 4, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}}},
	{Key: "MaximumRatIndex", Type: "int", Default: 25},
	{Key: "DaysUntilMaximumRatIndex", Type: "int", Default: 90},
	{Key: "MetaKnowledge", Type: "int", Default: 3, Options: []option{{1, "Fully revealed"}, {2, "Shown as ???"}, {3, "Completely hidden"}}},
	{Key: "SeeNotLearntRecipe", Type: "bool", Default: true},
	{Key: "MaximumLootedBuildingRooms", Type: "int", Default: 50},
	{Key: "EnablePoisoning", Type: "int", Default: 1, Options: []option{{1, "True"}, {2, "False"}, {3, "Only bleach poisoning is disabled"}}},
	{Key: "MaggotSpawn", Type: "int", Default: 1, Options: []option{{1, "In and Around Bodies"}, {2, "In Bodies Only"}, {3, "Never"}}},
	{Key: "LightBulbLifespan", Type: "float", Default: 2.0},
	{Key: "FishAbundance", Type: "int", Default: 2, Options: []option{{1, "Very Poor"}, {2, "Poor"}, {3, "Normal"}, {4, "Abundant"}, {5, "Very Abundant"}}},
	{Key: "LevelForMediaXPCutoff", Type: "int", Default: 3},
	{Key: "LevelForDismantleXPCutoff", Type: "int", Default: 0},
	{Key: "BloodSplatLifespanDays", Type: "int", Default: 0},
	{Key: "LiteratureCooldown", Type: "int", Default: 45},
	{Key: "NegativeTraitsPenalty", Type: "int", Default: 1, Options: []option{{1, "None"}, {2, "1 point penalty for every 3 negative traits selected"}, {3, "1 point penalty for every 2 negative traits selected"}, {4, "1 point penalty for every negative trait selected after the first"}}},
	{Key: "MinutesPerPage", Type: "float", Default: 2.0},
	{Key: "KillInsideCrops", Type: "bool", Default: true},
	{Key: "PlantGrowingSeasons", Type: "bool", Default: true},
	{Key: "PlaceDirtAboveground", Type: "bool", Default: false},
	{Key: "FarmingSpeedNew", Type: "float", Default: 1.0},
	{Key: "FarmingAmountNew", Type: "float", Default: 1.0},
	{Key: "MaximumLooted", Type: "int", Default: 25},
	{Key: "DaysUntilMaximumLooted", Type: "int", Default: 90},
	{Key: "RuralLooted", Type: "float", Default: 0.5},
	{Key: "MaximumDiminishedLoot", Type: "int", Default: 20},
	{Key: "DaysUntilMaximumDiminishedLoot", Type: "int", Default: 3650},
	{Key: "MuscleStrainFactor", Type: "float", Default: 0.7},
	{Key: "DiscomfortFactor", Type: "float", Default: 0.8},
	{Key: "WoundInfectionFactor", Type: "float", Default: 1.0},
	{Key: "NoBlackClothes", Type: "bool", Default: true},
	{Key: "EasyClimbing", Type: "bool", Default: false},
	{Key: "MaximumFireFuelHours", Type: "int", Default: 8},
	{Key: "FirearmUseDamageChance", Type: "int", Default: 2, Options: []option{{1, "Disabled"}, {2, "Zombies only"}, {3, "All types of target"}}},
	{Key: "FirearmNoiseMultiplier", Type: "float", Default: 1.0},
	{Key: "FirearmJamMultiplier", Type: "float", Default: 1.0},
	{Key: "FirearmMoodleMultiplier", Type: "float", Default: 1.0},
	{Key: "FirearmWeatherMultiplier", Type: "float", Default: 1.0},
	{Key: "FirearmHeadGearEffect", Type: "bool", Default: true},
	{Key: "ClayLakeChance", Type: "float", Default: 0.05},
	{Key: "ClayRiverChance", Type: "float", Default: 0.05},
	{Key: "GeneratorTileRange", Type: "int", Default: 20},
	{Key: "GeneratorVerticalPowerRange", Type: "int", Default: 3},
	{Key: "Basement.SpawnFrequency", Type: "int", Default: 4, Options: []option{{1, "Never"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}, {7, "Always"}}},
	{Key: "Map.AllowMiniMap", Type: "bool", Default: false},
	{Key: "Map.AllowWorldMap", Type: "bool", Default: true},
	{Key: "Map.MapAllKnown", Type: "bool", Default: false},
	{Key: "Map.MapNeedsLight", Type: "bool", Default: true},
	{Key: "ZombieLore.Speed", Type: "int", Default: 4, Options: []option{{1, "Sprinters"}, {2, "Fast Shamblers"}, {3, "Shamblers"}, {4, "Random"}}},
	{Key: "ZombieLore.SprinterPercentage", Type: "int", Default: 0},
	{Key: "ZombieLore.Strength", Type: "int", Default: 2, Options: []option{{1, "Superhuman"}, {2, "Normal"}, {3, "Weak"}, {4, "Random"}}},
	{Key: "ZombieLore.Toughness", Type: "int", Default: 4, Options: []option{{1, "Tough"}, {2, "Normal"}, {3, "Fragile"}, {4, "Random"}}},
	{Key: "ZombieLore.Transmission", Type: "int", Default: 1, Options: []option{{1, "Blood and Saliva"}, {2, "Saliva Only"}, {3, "Everyone's Infected"}, {4, "None"}}},
	{Key: "ZombieLore.Mortality", Type: "int", Default: 5, Options: []option{{1, "Instant"}, {2, "0-30 Seconds"}, {3, "0-1 Minutes"}, {4, "0-12 Hours"}, {5, "2-3 Days"}, {6, "1-2 Weeks"}, {7, "Never"}}},
	{Key: "ZombieLore.Reanimate", Type: "int", Default: 3, Options: []option{{1, "Instant"}, {2, "0-30 Seconds"}, {3, "0-1 Minutes"}, {4, "0-12 Hours"}, {5, "2-3 Days"}, {6, "1-2 Weeks"}}},
	{Key: "ZombieLore.Cognition", Type: "int", Default: 3, Options: []option{{1, "Navigate and Use Doors"}, {2, "Navigate"}, {3, "Basic Navigation"}, {4, "Random"}}},
	{Key: "ZombieLore.DoorOpeningPercentage", Type: "int", Default: 0},
	{Key: "ZombieLore.CrawlUnderVehicle", Type: "int", Default: 5, Options: []option{{1, "Crawlers Only"}, {2, "Extremely Rare"}, {3, "Rare"}, {4, "Sometimes"}, {5, "Often"}, {6, "Very Often"}, {7, "Always"}}},
	{Key: "ZombieLore.Memory", Type: "int", Default: 2, Options: []option{{1, "Long"}, {2, "Normal"}, {3, "Short"}, {4, "None"}, {5, "Random"}, {6, "Random between Normal and None"}}},
	{Key: "ZombieLore.Sight", Type: "int", Default: 5, Options: []option{{1, "Eagle"}, {2, "Normal"}, {3, "Poor"}, {4, "Random"}, {5, "Random between Normal and Poor"}}},
	{Key: "ZombieLore.Hearing", Type: "int", Default: 5, Options: []option{{1, "Pinpoint"}, {2, "Normal"}, {3, "Poor"}, {4, "Random"}, {5, "Random between Normal and Poor"}}},
	{Key: "ZombieLore.SpottedLogic", Type: "bool", Default: true},
	{Key: "ZombieLore.ThumpNoChasing", Type: "bool", Default: false},
	{Key: "ZombieLore.ThumpOnConstruction", Type: "bool", Default: true},
	{Key: "ZombieLore.ActiveOnly", Type: "int", Default: 1, Options: []option{{1, "Both"}, {2, "Night"}, {3, "Day"}}},
	{Key: "ZombieLore.TriggerHouseAlarm", Type: "bool", Default: true},
	{Key: "ZombieLore.ZombiesDragDown", Type: "bool", Default: true},
	{Key: "ZombieLore.ZombiesCrawlersDragDown", Type: "bool", Default: false},
	{Key: "ZombieLore.ZombiesFenceLunge", Type: "bool", Default: true},
	{Key: "ZombieLore.ZombiesArmorFactor", Type: "float", Default: 2.0},
	{Key: "ZombieLore.ZombiesMaxDefense", Type: "int", Default: 85},
	{Key: "ZombieLore.ChanceOfAttachedWeapon", Type: "int", Default: 6},
	{Key: "ZombieLore.ZombiesFallDamage", Type: "float", Default: 1.0},
	{Key: "ZombieLore.DisableFakeDead", Type: "int", Default: 1, Options: []option{{1, "World Zombies"}, {2, "World and Combat Zombies"}, {3, "Never"}}},
	{Key: "ZombieLore.PlayerSpawnZombieRemoval", Type: "int", Default: 1, Options: []option{{1, "Inside the building and around it"}, {2, "Inside the building"}, {3, "Inside the room"}, {4, "Zombies can spawn anywhere"}}},
	{Key: "ZombieLore.FenceThumpersRequired", Type: "int", Default: 25},
	{Key: "ZombieLore.FenceDamageMultiplier", Type: "float", Default: 1.0},
	{Key: "ZombieConfig.PopulationMultiplier", Type: "float", Default: 0.65},
	{Key: "ZombieConfig.PopulationStartMultiplier", Type: "float", Default: 1.0},
	{Key: "ZombieConfig.PopulationPeakMultiplier", Type: "float", Default: 1.5},
	{Key: "ZombieConfig.PopulationPeakDay", Type: "int", Default: 28},
	{Key: "ZombieConfig.RespawnHours", Type: "float", Default: 0.0},
	{Key: "ZombieConfig.RespawnUnseenHours", Type: "float", Default: 0.0},
	{Key: "ZombieConfig.RespawnMultiplier", Type: "float", Default: 0.0},
	{Key: "ZombieConfig.RedistributeHours", Type: "float", Default: 12.0},
	{Key: "ZombieConfig.FollowSoundDistance", Type: "int", Default: 100},
	{Key: "ZombieConfig.RallyGroupSize", Type: "int", Default: 20},
	{Key: "ZombieConfig.RallyGroupSizeVariance", Type: "int", Default: 50},
	{Key: "ZombieConfig.RallyTravelDistance", Type: "int", Default: 20},
	{Key: "ZombieConfig.RallyGroupSeparation", Type: "int", Default: 15},
	{Key: "ZombieConfig.RallyGroupRadius", Type: "int", Default: 3},
	{Key: "ZombieConfig.ZombiesCountBeforeDelete", Type: "int", Default: 300},
	{Key: "MultiplierConfig.Global", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.GlobalToggle", Type: "bool", Default: true},
	{Key: "MultiplierConfig.Fitness", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Strength", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Sprinting", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Lightfoot", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Nimble", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Sneak", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Axe", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Blunt", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.SmallBlunt", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.LongBlade", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.SmallBlade", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Spear", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Maintenance", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Woodwork", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Cooking", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Farming", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Doctor", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Electricity", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.MetalWelding", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Mechanics", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Tailoring", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Aiming", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Reloading", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Fishing", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Trapping", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.PlantScavenging", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.FlintKnapping", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Masonry", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Pottery", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Carving", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Husbandry", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Tracking", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Blacksmith", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Butchering", Type: "float", Default: 1.0},
	{Key: "MultiplierConfig.Glassmaking", Type: "float", Default: 1.0},
}
